
CLOSE_KEY = 27


KEYPOINT_DRAW_COLOR = (0, 0, 255)

BASE_DIR = "./sample"


MIN_MATCH_COUNT = 10
CURRENCY_DISPLAY_OFFSET_X = 10
CURRENCY_DISPLAY_OFFSET_Y = 10
CURRENCY_DISPLAY_COLOR = (0, 0, 0)
CURRENCY_CONT_COLOR = (0, 0, 255)
CURRENCY_CONT_THINKNESS = 3


DEBUG = False